### ISSUE TITLE
use config.ini  error

### ISSUE THREAD

**Issue by wangsrGit119** [mosajjal/arkime-container#1]
like:
```
docker run -it --rm -v $PWD/config.ini:/opt/arkime/etc/config.ini -v /opt/arkime/raw:/opt/arkime/raw --net host mosajjal/arkime:latest  --config=/opt/arkime/etc/config.ini
```
result:
```
unknown flag `config'
INFO[0000] setting interface parameters                 
INFO[0000] Starting the Capture process                 
INFO[0000] Starting the viewer process                  
panic: non-positive interval for NewTicker

goroutine 1 [running]:
time.NewTicker(0x12a05f200)
	/usr/local/go/src/time/tick.go:24 +0x10f
main.handler()
	/go/src/app/main.go:49 +0x49
main.main()
	/go/src/app/main.go:242 +0x271
(base) 

```

**Comment by mosajjal** [comment]
hi. `config` flag has been changed to `configPath`. I reflected the changes in the README as well. let me know if the new docs are not working.
